version: "3.4"
x-common-mysql-env: &common-mysql-env
  MYSQL_ROOT_PASSWORD: rootroot
  MYSQL_USER: localhost
  MYSQL_PASSWORD: root

services:
  mysql:
    container_name: mysql-local
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: myapp_db
      <<: *common-mysql-env
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
    ports:
      - 13306:3306
    command: --default-authentication-plugin=mysql_native_password


