

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:mysql://localhost:13306/myapp_db"
    username: "localhost"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  address: localhost
  port: 8888

---

spring:
  config:
    activate:
      on-profile: dev

my-app:
  welcome-message: "Hello, dev"
